# Generated by Django 5.2.6 on 2025-09-26 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=100)),
                ('tipo_refeicao', models.CharField(choices=[('marmita_pequena', 'Marmita Pequena'), ('marmita_grande', 'Marmita Grande'), ('pf', 'Prato Feito')], max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cartao', 'Cartão')], max_length=20)),
                ('entrega', models.CharField(choices=[('retirada', 'Retirada'), ('delivery', 'Delivery')], max_length=20)),
                ('proteina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cardapio.proteina')),
            ],
        ),
    ]
