# Generated by Django 5.2.6 on 2025-09-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='proteina',
        ),
        migrations.AddField(
            model_name='pedido',
            name='proteinas',
            field=models.ManyToManyField(to='cardapio.proteina'),
        ),
    ]
