# Generated by Django 5.2.6 on 2025-10-01 02:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_remove_pedido_proteina_pedido_proteinas'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
